apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-proxy
  namespace: kube-system
data:
  config.conf: |
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    mode: "iptables"
    clusterCIDR: "10.0.0.0/16"
    clientConnection:
      kubeconfig: "/var/lib/kube-proxy/kube-proxy.kubeconfig"
