apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    k8s-app: kube-proxy
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy
  template:
    metadata:
      labels:
        k8s-app: kube-proxy
    spec:
      hostNetwork: true
      serviceAccountName: kube-proxy
      containers:
      - name: kube-proxy
        image: registry.k8s.io/kube-proxy:v1.33.1
        command:
        - /usr/local/bin/kube-proxy
        - --config=/var/lib/kube-proxy/config.conf
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kube-proxy
          name: kube-proxy-config
        - name: xtables-lock
          mountPath: /run/xtables.lock
      volumes:
      - name: kube-proxy-config
        configMap:
          name: kube-proxy
          items:
          - key: config.conf
            path: config.conf
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
