version: '3'

vars:
  CLUSTER_NAME: '{{.CLUSTER_NAME | default "k8s-cluster"}}'
  WORKER_COUNT:
    sh: |
      if command -v yq >/dev/null 2>&1; then
        yq -r '.WorkerNodeCount' ./config.yaml
      else
        awk '/WorkerNodeCount/ {print $2; exit}' ./config.yaml
      fi
  WORKER_HOSTS:
    sh: |
      workers=""
      for i in $(seq 1 {{.WORKER_COUNT}}); do
        workers+=" worker$i"
      done
      echo "$workers"
  CERT_PATH: './certs'
  KUBECONFIG_PATH: './kubeconfigs'
  UNIT_PATH: './units'
  SSH_PARAMS: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  
includes:
  certificates: tasks/certificates.taskfile.yml
  kubectl: tasks/kubectl.taskfile.yml
  networking: tasks/networking.taskfile.yml
  vms: tasks/vms.taskfile.yml
  tests: tasks/tests.taskfile.yml

tasks:  
  build:
    desc: "Build / Turn on VMs for K8s cluster"
    cmds:
      - task: vms:start:all
      - vagrant snapshot push
      - task: networking:config
      - task: certificates:gen
      - task: vms:install:master
      - task: vms:install:workers
  
  destroy:
    cmds:
      - task: vms:destroy:all
        ignore_error: true
      - task: certificates:clean
        ignore_error: true
      - task: networking:clean
        ignore_error: true
      - task: kubectl:clean
        ignore_error: true
      - cmd: rm -f ./scripts/local/{hosts,*.sh}
        ignore_error: true
      - cmd: rm -f ./machines.txt
        ignore_error: true
