version: '3'

tasks:
  config:
    desc: "Configure kubectl"
    vars:
      K8S_CLUSTER_NAME: '{{.K8S_CLUSTER_NAME | default "k8s-cluster"}}'
      CERT_ORIGINAL_DIR: "/vagrant/certs"
    status:
      - |
        if command -v kubectl >/dev/null 2>&1; then
          exit 1
        fi
        exit 0
    cmds:
      - |
        MASTER_IP=$(grep 'master' ./machines.txt | awk '{print $1}')
        echo "Extracted MASTER_IP: $MASTER_IP"

        kubectl config set-cluster {{.K8S_CLUSTER_NAME}} \
            --certificate-authority={{.CERT_ORIGINAL_DIR}}/ca.crt \
            --embed-certs=true \
            --server=https://$MASTER_IP:6443
      - |
        kubectl config set-credentials admin \
          --client-certificate={{.CERT_ORIGINAL_DIR}}/admin.crt \
          --client-key={{.CERT_ORIGINAL_DIR}}/admin.key
      - |
        kubectl config set-context {{.K8S_CLUSTER_NAME}} \
          --cluster={{.K8S_CLUSTER_NAME}} \
          --user=admin
      - kubectl config use-context {{.K8S_CLUSTER_NAME}}
