version: '3'

tasks:
  gen:
    desc: "Generate CA and certificates for Kubernetes components"
    vars:
      MASTER_IP:
        sh: |
          {{.MASTER_IP_CMD}}
      MASTER_FQDN:
        sh: |
          {{.MASTER_FQDN_CMD}}
      POD_CIDR:
        sh: |
          {{.POD_CIDR_CMD}}
      CERT_COMPONENTS: "admin kube-proxy kube-scheduler kube-controller-manager kube-api-server etcd service-accounts"
    status:
      - test -f ./machines.txt
      - |
        # Check if ANY of the cert files exist
        for prefix in {{.CERT_COMPONENTS}}; do
          for ext in crt key csr; do
            if [ -f "{{.CERT_PATH}}/${prefix}.${ext}" ]; then
              exit 0  # File found → task is up to date → skip it
            fi
          done
        done
        exit 1  # No files found → task is stale → run it
    cmds:
      - |
        FIRST_IP=$(echo {{.POD_CIDR}} | cut -d '.' -f 1-3).1

        echo "Generating certificates config file..."
        sed -e "s/{MASTER_IP}/{{.MASTER_IP}}/g" -e "s/{MASTER_FQDN}/{{.MASTER_FQDN}}/g" -e "s/{POD_CIDR_FIRST_IP}/$FIRST_IP/g" ca.conf > /tmp/ca.conf
      - |
        echo "# Create CA on Host"
        echo "## Create the CA Private Key"
        openssl genrsa -out "{{.CERT_PATH}}/ca.key" 4096

        echo "## Generate the CA Self-Signed Certificate"
        openssl req -x509 -new -sha512 -noenc \
            -key "{{.CERT_PATH}}/ca.key" -days 3653 \
            -config "/tmp/ca.conf" \
            -out "{{.CERT_PATH}}/ca.crt"
      
      - |
        for component in {{.CERT_COMPONENTS}}; do
          echo "# Create certificates for $component"
          openssl genrsa -out "{{.CERT_PATH}}/$component.key" 4096

          openssl req -new -key "{{.CERT_PATH}}/$component.key" -sha256 \
            -config "/tmp/ca.conf" -section $component \
            -out "{{.CERT_PATH}}/$component.csr"

          openssl x509 -req -days 3653 -in "{{.CERT_PATH}}/$component.csr" \
            -copy_extensions copyall \
            -sha256 -CA "{{.CERT_PATH}}/ca.crt" \
            -CAkey "{{.CERT_PATH}}/ca.key" \
            -CAcreateserial \
            -out "{{.CERT_PATH}}/$component.crt"
        done
      - task: tls-bootstrap
        
  tls-bootstrap:
    desc: "Generate TLS bootstrap certificates"
    generate:
      - ./bootstrap_token.yaml
    cmds:
      - |
        generate_random_string() {
          local length=$1
          tr -dc 'a-z0-9' </dev/urandom | head -c "$length"
        }
        TOKEN_ID=$(generate_random_string 6)
        TOKEN_SECRET=$(generate_random_string 16)
        BOOTSTRAP_TOKEN="${TOKEN_ID}.${TOKEN_SECRET}"
        EXPIRATION=$(date -u --date "+30 days" +"%Y-%m-%dT%H:%M:%SZ")
        
        cat <<EOF > bootstrap_token.yaml
        bootstrap_token: ${BOOTSTRAP_TOKEN}
        expiration: ${EXPIRATION}
        EOF

        sed \
          -e "s/{TOKEN_ID}/$TOKEN_ID/g" \
          -e "s/{TOKEN_SECRET}/$TOKEN_SECRET/g" \
          -e "s/{EXPIRATION}/$EXPIRATION/g" \
          {{.CONFIG_PATH}}/bootstrap-token.template.yaml > "{{.CONFIG_PATH}}/bootstrap-token-${TOKEN_ID}.yaml"

  clean:
    desc: "Clean up generated certificates"
    cmds:
      - rm -f {{.CERT_PATH}}/*.key {{.CERT_PATH}}/*.crt {{.CERT_PATH}}/*.csr {{.CERT_PATH}}/ca.key {{.CERT_PATH}}/ca.crt {{.CERT_PATH}}/ca.srl
      - rm -f ./bootstrap-token-*.yaml
