version: '3'

tasks:
  config:
    desc: "Configure kubectl"
    vars:
      MASTER_FQDN:
        sh: awk '/ master /{print $3}' ./machines.txt
    status:
      - |
        if command -v kubectl >/dev/null 2>&1; then
          exit 1
        fi
        exit 0
    cmds:
      - |
        kubectl config set-cluster {{.CLUSTER_NAME}} \
            --certificate-authority={{.CERT_PATH}}/ca.crt \
            --embed-certs=true \
            --server=https://{{.MASTER_FQDN}}:6443
      - |
        kubectl config set-credentials admin \
          --client-certificate={{.CERT_PATH}}/admin.crt \
          --client-key={{.CERT_PATH}}/admin.key
      - |
        kubectl config set-context {{.CLUSTER_NAME}} \
          --cluster={{.CLUSTER_NAME}} \
          --user=admin
      - kubectl config use-context {{.CLUSTER_NAME}}

  clean:
    desc: "Clean up kubectl config"
    cmds:
      - kubectl config delete-context {{.CLUSTER_NAME}}
      - kubectl config delete-cluster {{.CLUSTER_NAME}}
      - kubectl config delete-user admin
