version: '3'

tasks:
  config:
    desc: "Configure networking"
    sources:
      - ./machines.txt
    status:
      - '! test -f ./machines.txt'
    cmds:
      - task: config:kube-proxy
      - task: config:kube-apiserver
      - task: config:kube-controller-manager

  config:kube-proxy:
    desc: "Configure kube-proxy"
    vars:
      POD_CIDR:
        sh: |
          {{.POD_CIDR_CMD}}
    cmds:
      - sed "s#{POD_CIDR}#{{.POD_CIDR}}#g" {{.CONFIG_PATH}}/kube-proxy-config.template.yaml > {{.CONFIG_PATH}}/kube-proxy-config.yaml

  config:kube-apiserver:
    desc: "Configure kube-apiserver"
    vars:
      MASTER_IP:
        sh: |
          {{.MASTER_IP_CMD}}
      MASTER_FQDN:
        sh: |
          {{.MASTER_FQDN_CMD}}
      SERVICE_CIDR:
        sh: |
          {{.SERVICE_CIDR_CMD}}
    cmds:
      - |        
        sed "s#{MASTER_IP}#{{.MASTER_IP}}#g; s#{MASTER_FQDN}#{{.MASTER_FQDN}}#g; s#{SERVICE_CIDR}#{{.SERVICE_CIDR}}#g" \
          {{.UNIT_PATH}}/kube-apiserver.template.service > \
          {{.UNIT_PATH}}/kube-apiserver.service

  config:kube-controller-manager:
    desc: "Configure kube-controller-manager"
    vars:
      POD_CIDR:
        sh: |
          {{.POD_CIDR_CMD}}
      SERVICE_CIDR:
        sh: |
          {{.SERVICE_CIDR_CMD}}
    cmds:
      - |        
        sed "s#{POD_CIDR}#{{.POD_CIDR}}#g; s#{SERVICE_CIDR}#{{.SERVICE_CIDR}}#g" \
          "{{.UNIT_PATH}}/kube-controller-manager.template.service" > \
          "{{.UNIT_PATH}}/kube-controller-manager.service"

  clean:
    desc: "Clean up networking configuration"
    cmds:
      - rm -f ./configs/kube-proxy-config.yaml
      - rm -f {{.UNIT_PATH}}/kube-apiserver.service
      - rm -f {{.UNIT_PATH}}/kube-controller-manager.service
